### ISSUE TITLE
Equipo 3

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-3#1]

**Comment by AmeliReyesHernandez** [comment]
[Nota Informativa Equipo 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-3/files/9955602/Nota.Informativa.Equipo.3.pdf)

**Comment by MarleneRamirez0731** [comment]
> [Nota Informativa Equipo 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-3/files/9955602/Nota.Informativa.Equipo.3.pdf)
> 

 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
